### ISSUE TITLE
Git tags for releases

### ISSUE THREAD

**Issue by thjaeckle** [arnohaase/simple-akka-downing#2]
Hi.

I just stumbled upon this library when trying to add a downing strategy for [Eclipse Ditto](https://github.com/eclipse/ditto) using Akka and I really like it.
I noticed that the latest release on Maven central is 0.9.2, but this is not reflected in a tag or release here at Github.
Would it be possible to add tags when releasing (or do you still know for the old releases at which commit they were made in order to publish them)?

Best regards
Thomas

**Comment by bekiroguz** [comment]
Hi Thomas,
if you would like to give a try to another open source akka-downing solution, you can look at [Baker](https://github.com/ing-bank/baker) split brain resolver. If "Majority" strategy is good for you, this may be worth to look at, please check the documentation of the [Baker](https://ing-bank.github.io/baker/) library and [Split-Brain-Resolver](https://ing-bank.github.io/baker/documentation/split-brain-resolver/).

**Comment by thjaeckle** [comment]
Thanks for the hint.
I like at this one in this repo that no other dependencies are required apart from the Akka ones we already have.

**Comment by bekiroguz** [comment]
Ok, it is up to you to choose of course. As a side note, baker sbr is a submodule of the main baker library but it has no dependencies to baker. Only dependencies are akka actors and akka cluster.

**Comment by thjaeckle** [comment]
> Ok, it is up to you to choose of course. As a side note, baker sbr is a submodule of the main baker library but it has no dependencies to baker. Only dependencies are akka actors and akka cluster.

And to `com.iheart:ficus_2.12:1.4.0` ;)

**Comment by arnohaase** [comment]
Thanks for pointing this out - not sure why the tags didn't get created when I published, but I added the tag for 9.2 manually.
And thanks for the friendly feedback ;-) !
